spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testingacc4now@gmail.com
    password: syqx rkcg knjq nyzd
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=webtrunggian_v2;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 9999
  error:
    include-message: always
    include-binding-errors: always
